spring.application.name=ms-productos
server.port=8081

# Persistencia Real (IE 2.1.1)
spring.datasource.url=jdbc:mysql://localhost:3306/db_productos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tu_clave_aqui
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Trazabilidad y Logs (IE 2.3.2)
logging.level.com.duoc.ms_productos=DEBUG
logging.file.name=logs/ms-productos.log
